### ISSUE TITLE
docker registry connection refused deis on kubernetes aws

### ISSUE THREAD

**Issue by anubhavmishra** [deis/registry#89] opened 2017-04-21 06:48 UTC
I have installed workflow using helm. It is using the default backed. I am going through the example go app and seeing an error. Here are the commands:
```bash
$ deis create --no-remote
Creating Application... done, created golden-utensils
If you want to add a git remote for this app later, use `deis git:remote -a golden-utensils`
$ deis pull deis/example-go -a golden-utensils
Creating build... Error: Unknown Error (400): {"detail":"Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused"}
```

controller logs:
```bash
10.240.1.1 "POST /v2/hooks/config/ HTTP/1.1" 200 227 "deis-builder"
INFO [golden-utensils]: build golden-utensils-d541346 created
INFO:api.models.app:[golden-utensils]: build golden-utensils-d541346 created
INFO [golden-utensils]: admin deployed deis/example-go
INFO:api.models.app:[golden-utensils]: admin deployed deis/example-go
INFO Pulling Docker image deis/example-go:latest
INFO:registry.dockerclient:Pulling Docker image deis/example-go:latest
INFO Tagging Docker image deis/example-go:latest as 127.0.0.1:5555/golden-utensils:v3
INFO:registry.dockerclient:Tagging Docker image deis/example-go:latest as 127.0.0.1:5555/golden-utensils:v3
INFO Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
INFO:registry.dockerclient:Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
ERROR:backoff._common:Backing off push(...) for 0.3s (registry.dockerclient.RegistryException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused)
INFO Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
INFO:registry.dockerclient:Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
ERROR:backoff._common:Backing off push(...) for 0.9s (registry.dockerclient.RegistryException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused)
INFO Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
INFO:registry.dockerclient:Pushing Docker image 127.0.0.1:5555/golden-utensils:v3
ERROR:backoff._common:Giving up push(...) after 3 tries (registry.dockerclient.RegistryException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused)
INFO [golden-utensils]: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused
INFO:api.models.app:[golden-utensils]: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused
ERROR:root:Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused
Traceback (most recent call last):
  File "/app/api/models/release.py", line 89, in new
    release.publish()
  File "/app/api/models/release.py", line 136, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 195, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 114, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/usr/local/lib/python3.5/dist-packages/backoff/_sync.py", line 85, in retry
    ret = target(*args, **kwargs)
  File "/app/registry/dockerclient.py", line 131, in push
    log_output(stream, 'push', repo, tag)
  File "/app/registry/dockerclient.py", line 174, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 191, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 63, in create
    source_version=self.version
  File "/app/api/models/release.py", line 96, in new
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 185, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 268, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 79, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://127.0.0.1:5555/v1/repositories/golden-utensils/: dial tcp 127.0.0.1:5555: getsockopt: connection refused
10.240.1.1 "POST /v2/apps/golden-utensils/builds/ HTTP/1.1" 400 128 "Deis Client v2.13.0"
```

**Comment by bacongobbler** [comment] 2017-04-21 14:42
Hey, have you taken a look at #64? On some platforms host ports are unavailable, so I've supplied a workaround for those situations.

**Comment by anubhavmishra** [comment] 2017-04-21 16:32
@bacongobbler thanks for your help. We will wait for CNI issues to be resolved. For now I can try the suggestion here: https://github.com/deis/registry/issues/64#issuecomment-254916941

**Comment by bacongobbler** [comment] 2017-04-21 16:59
closing as a duplicate of #64.

**Closed as completed by bacongobbler** 2017-04-21 16:59 UTC
